siteurl: ''
publicDir: 'public'
contentDir: 'content'
staticDir: 'static'
summaryLength: 300
siteTitle: 'Objecteam'
dateFormat: 'LL'
languages:
    - path: '/en/'
      locale: 'en'
      name: 'English'
    # - path: '/'
    #   locale: 'el'
    #   name: 'Greek'
defaultLanguage: 'el'
